name: dayder
description: daily announcement.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  #https://pub.dev/packages/riverpod
  riverpod: ^2.4.6
  #https://pub.dev/packages/flutter_riverpod
  flutter_riverpod: ^2.4.6
  #https://pub.dev/packages/json_annotation
  json_annotation: ^4.8.1
  #https://pub.dev/packages/get_it
  get_it: ^7.6.4
  #https://pub.dev/packages/google_fonts
  google_fonts: ^6.1.0
  #https://pub.dev/packages/auto_route
  auto_route: ^7.8.4
  #https://pub.dev/packages/logger
  logger: ^2.0.2+1
  #https://pub.dev/packages/flex_color_scheme
  flex_color_scheme: ^7.3.1
  #https://pub.dev/packages/firebase_core
  firebase_core: ^2.22.0
  #https://pub.dev/packages/firebase_crashlytics
  firebase_crashlytics: ^3.4.4
  #https://pub.dev/packages/firebase_auth
  firebase_auth: ^4.14.0
  #https://pub.dev/packages/freezed_annotation
  freezed_annotation: ^2.4.1
  #https://pub.dev/packages/faker
  faker: ^2.1.0
  #https://pub.dev/packages/riverpod_annotation
  riverpod_annotation: ^2.3.1
  #https://pub.dev/packages/cloud_firestore
  cloud_firestore: ^4.13.1
  #https://pub.dev/packages/firebase_storage
  firebase_storage: ^11.5.1
  #https://pub.dev/packages/flutter_hooks
  flutter_hooks: ^0.20.3
  #https://pub.dev/packages/hooks_riverpod
  hooks_riverpod: ^2.4.8
  #https://pub.dev/packages/uuid
  uuid: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  #https://pub.dev/packages/build_runner
  build_runner: ^2.4.6
  #https://pub.dev/packages/freezed
  freezed: ^2.4.5
  #https://pub.dev/packages/json_serializable
  json_serializable: ^6.7.1
  #https://pub.dev/packages/auto_route_generator
  auto_route_generator: ^7.3.2
  #https://pub.dev/packages/riverpod_generator
  riverpod_generator: ^2.3.6

flutter:
  uses-material-design: true
  assets:
    - assets/
